kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - go get code.nfsmith.ca/nsmith/mjpeg
  - CGO_ENABLED=0 go build -o main *.go
- name: publish
  image: plugins/docker
  settings:
    repo: registry.nfsmith.ca/ising
    registry: registry.nfsmith.ca
    auto_tag: true
    secrets: [docker_username, docker_password]
